# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.IntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('openning_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
