# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default=b'Tweet missing', max_length=200),
        ),
    ]
