# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160515_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tint',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
